[build]
builder = "NIXPACKS"

[build.command]
cmd = "npm run build"

[deploy]
startCommand = "node src/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
